!!python/object:argparse.Namespace
alpha: 0.6
b: 0.04
batch_size: 1000
gamma: 3
initial_lr: 0.005
lookback: 20
lstm_hidden_size: 15
n_epochs: 20000
num_nodes: 3
number_regressor_layers: 2
output_training_file_name: ./results/metrics_test_184.txt
output_validation_file_name: ./results/metrics_test_184_valid.txt
patience: 50
regressor_hidden_size: 512
regressor_hidden_size_2: 512
scheduler_gamma: 0.9
scheduler_milestone_frequency: 130
scheduler_number_of_updates: 60
sigma: 0.14
steps_ahead: 2
steps_filename: 1
test_number: 184
train_split: 0.8
v_0: 0.04
validation_every: 50
years: 60
