!!python/object:argparse.Namespace
alpha: 0.6
b: 0.02
conditioning: true
contract_frequency: 150
conv_aggr: mean
conv_num_layers: 1
dataset_gamma: 3.0
dataset_name: synthetic
dataset_nodes: 2
delta: 0
dropout_p: 0.5
edge_window_size: 1
eval_every: 10
gamma: 0.4
hidden_channels:
- 128
hidden_feats: 32
initial_lr: 5e-3
k_chebyshev: 3
loss_class_weights:
- 1
- 1
lr: 0.01
lstm_hidden_size: 15
lstm_num_layers: 2
lstm_out_channels: null
maximum_degree_btc: 146
model_name: DyGrEncoder
n_epochs: 20000
neg_mult_eval: 10000000000
neg_mult_training: 100
num_hist_steps: 50
num_of_epochs: 1000
number_of_layers: 1
number_of_predictions: 1
number_regressor_layers: 2
out_channels: 128
output_training_file_name: ./results/metrics_test_4.txt
output_validation_file_name: ./results/metrics_test_4_valid.txt
patience: 7
regressor_hidden_size: 512
regressor_hidden_size_2: 512
scheduler_gamma: 0.9
scheduler_milestone_frequency: 130
scheduler_number_of_updates: 60
sigma: 0.14
test_number: 4
time_frequency: 86400
train_split: 0.8
v_0: 0.04
val_split: 0.2
validation_every: 50
years: 3
