# Local / cluster machine parameters
device : cuda
safe_gpu_load: False

#Dataset params
dataset_name : BTC               # possibilities: BTC | MOOC | LastFM | wikipedia
time_frequency : 86400              #  =3600 * 24   The time frequency in which to gather data (typically a day in seconds)
maximum_degree_btc : 146              # Largest node degree found throughout all the time steps
edge_window_size : 1              # Number of time steps in which we should aggregate the edge informations

# Get Sample parameters
neg_mult_training : 100           # Neg_mult for training 
neg_mult_eval : 10000000000        # Neg_mult for eval (if very high == num_nodes**2)

# Splitter params
train_split : 0.8                 # Training split
val_split : 0.2                   # validation split, not used if `no_test == True`
num_hist_steps : 1              # How many steps in the past a single DataPoint will be made of, basically it is the number of steps the model is using to learn the GRU parameters

# Extrapolation params
number_of_predictions: 6
extrapolation : True             # Wheter to feed the evolveGCNH with its own node embeddings

# Cross entropy params
loss_class_weights : [1, 1]   # weights for compensating class unbalancement

# Model params
model_name : EdgeCNN
number_of_layers : 2              # Number of convolutional layers for evolveGCNH model
hidden_channels : [64]            # Hidden size of EvolveGCNH TO TUNE (list)
out_channels : 32                 # Output size of the node embeddings TO TUNE
k_chebyshev : 3                   # K parameter for chebyshev polynomial truncation (3 in the GC-LSTM paper)
dropout_p : 0.5                   # Dropout probability
conv_num_layers: 2
conv_aggr: mean
lstm_num_layers: 1

# Classifier params
hidden_feats : 32                # Hidden dim of classifier layer TO TUNE

# Optimizer params
lr: 0.0001                         # Learning rate for the adam optimizer

# Training params
num_of_epochs : 300               # Number of epochs for a training session
eval_every : 25                   # Number of epochs after which evaluation must be performed


