# Simulation parameters
alpha : 0.6
b : 0.04
sigma : 0.14
v_0 : 0.04
years : 20
gamma : 3
#######################
#Dataset parameters
steps_ahead : 5
steps_filename : 1
num_nodes : 5
lookback : 5
train_split : 0.8

#######################
#Model parameters
lstm_hidden_size : 15
regressor_hidden_size : 512
regressor_hidden_size_2 : 512
number_regressor_layers : 2
input_size : 36
contract_size : 6

#######################
#Training parameters
initial_lr : 0.005 #5e-3
n_epochs : 20000
patience : 50
scheduler_milestone_frequency : 130
scheduler_number_of_updates : 60
scheduler_gamma : 0.9
validation_every : 20
batch_size : 500

device: 'cuda:0'
